# Generated by Django 5.1.1 on 2024-10-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/images/thumb.jpg', upload_to='blog/images/'),
        ),
    ]
